branch-defaults:
  default:
    environment: my-flask-env
environment-defaults:
  my-flask-env:
    branch: null
    repository: null
global:
  application_name: paysub
  default_ec2_keyname: aws-eb
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
